fii_analyst_task:
  description: >
    Receive detailed financial data and relevant information about specific FIIs.
    Check if the information is correct with the current date {date}.
    Evaluate the data to determine if each FII is a good investment opportunity right now, considering the date {date}.
    Provide a clear recommendation: "Buy" or "Do Not Invest," along with a brief rationale to support your decision.
  agent: fii_analyst
  input:
    - fii_name
    - financial_metrics
    - market_trends
    - historical_performance
  expected_output: >
    A decision indicating whether the FII is a good investment ("Buy" or "Do Not Invest"), along with a concise justification explaining the reasoning behind the decision.

report_writer_task:
  description: >
    Aggregate the decisions and justifications provided by the task fii_analyst_task for all analyzed FIIs.
    Compile these insights into a professionally written report, ensuring clarity, conciseness, and visual appeal.
    The report should highlight key opportunities, risks, and provide an overall information. 
    The information should be restricted to what the task fii_analyst_task returned.
    
  agent: report_writer
  input:
    - fii_analysis_results
  expected_output: >
    A final report summarizing all analyzed FIIs, including the investment decisions and justifications, along with an executive summary highlighting the key insights, as also
    the main values from each fii, like:
    - Preço Atual
    - Variação de Preço no Ano
    - Volume
    - Pagamento de Dividendos
    - Dividend Yield
