fii_info_scrapper_task:
  description: >
    For the provided list of FIIs {fiis} and the target date {date}, scrape detailed and accurate information that covers both technical metrics and qualitative insights.
      
      The task must collect, but is not limited to, the following data:
      
      - **Price Metrics:** 
        - Current trading price 
        - Historical price variation over relevant periods 
        - Trading volume
      
      - **Property Metrics:**
        - Vacancy rates
        - Recent property transactions
        - Occupancy levels
      
      - **Management and Administration:**
        - Changes or updates in the management or administration structure
      
      - **Reports and Announcements:**
        - Key highlights from the latest financial reports and public announcements
      
      - **Market Analysis:**
        - Overall market expectations and trends
        - Specialist opinions and insights
      
      Ensure the scraped data is accurate, well-structured, and presented in a format that allows an investment analyst to determine if it is an optimal time to invest in each FII. All information should reflect the conditions as of {date}.
  expected_output: >
    A JSON-like object with a detailed structure for each FII. For example:
      [
        {
          "fii_name": "FII Example",
          "price_info": {
            "current_price": "R$XX,XX",
            "price_change": "Y%",
            "volume": "Z units"
          },
          "property_metrics": {
            "vacancy_rate": "A%",
            "recent_transactions": "List of recent property transactions",
            "occupancy_rate": "B%"
          },
          "management_info": {
            "management_changes": "Details of any recent changes",
            "administrative_updates": "Summary of updates"
          },
          "report_highlights": "Summary of key points from financial reports and announcements",
          "market_analysis": {
            "market_expectations": "Overview of current market trends and expectations",
            "specialist_opinions": ["Opinion 1", "Opinion 2", "..."]
          }
        },
        {
          "fii_name": "...",
          ...
        }
      ]
  agent: fii_info_scrapper
